### ISSUE TITLE
Context requirement for function templates

### ISSUE THREAD

**Issue by darfink** [dflemstr/v8-rs#13] opened 2016-11-17 17:54 UTC
I've been thinking about the context requirement for `FunctionTemplate`. From what I can tell by analysing the source code, the context is required because an object is created to map the callback and its associated context together.

Because of this you cannot create a `FunctionTemplate` without a reference, and it removes the ability to reuse templates between contexts. This creates some issues (from the top of my head):
- The `HasInstance` method (corresponding to JavaScript's `instanceof`) cannot be used between objects from different contexts.
- You need to allocate a new object (and templates) even for those which have a static lifetime (e.g a `console`-like object).

I was thinking about analysing the code to decide whether this dependency can be removed, but I assume it was created for an educated reason in the first place.

**Comment by dflemstr** [comment] 2016-11-17 18:57
I remember there being a subtle reason why a context was needed, there was some interesting dependency on a thread local Isolate internal that segfaulted without having a context scope. Maybe the root cause is actually the object allocation you talked about and it might be worth investigating using some External wrapping a struct instead.

**Comment by dflemstr** [comment] 2017-02-25 21:08
Closing this because of lack of progress.

**Closed by dflemstr** 2017-02-25 21:08 UTC
